---
- hosts: test-servers
  become: true
  vars: 
    ansible_become_pass: Freya
  tasks:
    - name : install nginx
      package: pkg=nginx state=present
      
      notify:
       - start nginx
  handlers:
   - name: start nginx
     service: name=nginx state=started

